blank_issues_enabled: false
contact_links:
  - name: Lyrion Community Forum
    url: https://forums.lyrion.org
    about: 👉🏼 Please ask and answer questions in the forum, where you'll find a great and helpful community.
