# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.08) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory

#
# Generated from /tmp/HahUrb_roy/asia.  Olson data version 2025c
#
# Do not edit this file directly.
#
package DateTime::TimeZone::Asia::Manila;

use strict;
use warnings;
use namespace::autoclean;

our $VERSION = '2.66';

use Class::Singleton 1.03;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::Asia::Manila::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
    [
DateTime::TimeZone::NEG_INFINITY, #    utc_start
58191062168, #      utc_end 1844-12-31 15:56:08 (Tue)
DateTime::TimeZone::NEG_INFINITY, #  local_start
58191004800, #    local_end 1844-12-31 00:00:00 (Tue)
-57368,
0,
'LMT',
    ],
    [
58191062168, #    utc_start 1844-12-31 15:56:08 (Tue)
59916600000, #      utc_end 1899-09-06 04:00:00 (Wed)
58191091200, #  local_start 1845-01-01 00:00:00 (Wed)
59916629032, #    local_end 1899-09-06 12:03:52 (Wed)
29032,
0,
'LMT',
    ],
    [
59916600000, #    utc_start 1899-09-06 04:00:00 (Wed)
61089004800, #      utc_end 1936-10-31 16:00:00 (Sat)
59916628800, #  local_start 1899-09-06 12:00:00 (Wed)
61089033600, #    local_end 1936-11-01 00:00:00 (Sun)
28800,
0,
'PST',
    ],
    [
61089004800, #    utc_start 1936-10-31 16:00:00 (Sat)
61095567600, #      utc_end 1937-01-15 15:00:00 (Fri)
61089037200, #  local_start 1936-11-01 01:00:00 (Sun)
61095600000, #    local_end 1937-01-16 00:00:00 (Sat)
32400,
1,
'PDT',
    ],
    [
61095567600, #    utc_start 1937-01-15 15:00:00 (Fri)
61250659200, #      utc_end 1941-12-15 16:00:00 (Mon)
61095596400, #  local_start 1937-01-15 23:00:00 (Fri)
61250688000, #    local_end 1941-12-16 00:00:00 (Tue)
28800,
0,
'PST',
    ],
    [
61250659200, #    utc_start 1941-12-15 16:00:00 (Mon)
61255666800, #      utc_end 1942-02-11 15:00:00 (Wed)
61250691600, #  local_start 1941-12-16 01:00:00 (Tue)
61255699200, #    local_end 1942-02-12 00:00:00 (Thu)
32400,
1,
'PDT',
    ],
    [
61255666800, #    utc_start 1942-02-11 15:00:00 (Wed)
61352089200, #      utc_end 1945-03-03 15:00:00 (Sat)
61255699200, #  local_start 1942-02-12 00:00:00 (Thu)
61352121600, #    local_end 1945-03-04 00:00:00 (Sun)
32400,
0,
'JST',
    ],
    [
61352089200, #    utc_start 1945-03-03 15:00:00 (Sat)
61375590000, #      utc_end 1945-11-30 15:00:00 (Fri)
61352121600, #  local_start 1945-03-04 00:00:00 (Sun)
61375622400, #    local_end 1945-12-01 00:00:00 (Sat)
32400,
1,
'PDT',
    ],
    [
61375590000, #    utc_start 1945-11-30 15:00:00 (Fri)
61639459200, #      utc_end 1954-04-11 16:00:00 (Sun)
61375618800, #  local_start 1945-11-30 23:00:00 (Fri)
61639488000, #    local_end 1954-04-12 00:00:00 (Mon)
28800,
0,
'PST',
    ],
    [
61639459200, #    utc_start 1954-04-11 16:00:00 (Sun)
61644121200, #      utc_end 1954-06-04 15:00:00 (Fri)
61639491600, #  local_start 1954-04-12 01:00:00 (Mon)
61644153600, #    local_end 1954-06-05 00:00:00 (Sat)
32400,
1,
'PDT',
    ],
    [
61644121200, #    utc_start 1954-06-04 15:00:00 (Fri)
62364009600, #      utc_end 1977-03-27 16:00:00 (Sun)
61644150000, #  local_start 1954-06-04 23:00:00 (Fri)
62364038400, #    local_end 1977-03-28 00:00:00 (Mon)
28800,
0,
'PST',
    ],
    [
62364009600, #    utc_start 1977-03-27 16:00:00 (Sun)
62379385200, #      utc_end 1977-09-21 15:00:00 (Wed)
62364042000, #  local_start 1977-03-28 01:00:00 (Mon)
62379417600, #    local_end 1977-09-22 00:00:00 (Thu)
32400,
1,
'PDT',
    ],
    [
62379385200, #    utc_start 1977-09-21 15:00:00 (Wed)
62778902400, #      utc_end 1990-05-20 16:00:00 (Sun)
62379414000, #  local_start 1977-09-21 23:00:00 (Wed)
62778931200, #    local_end 1990-05-21 00:00:00 (Mon)
28800,
0,
'PST',
    ],
    [
62778902400, #    utc_start 1990-05-20 16:00:00 (Sun)
62784860400, #      utc_end 1990-07-28 15:00:00 (Sat)
62778934800, #  local_start 1990-05-21 01:00:00 (Mon)
62784892800, #    local_end 1990-07-29 00:00:00 (Sun)
32400,
1,
'PDT',
    ],
    [
62784860400, #    utc_start 1990-07-28 15:00:00 (Sat)
DateTime::TimeZone::INFINITY, #      utc_end
62784889200, #  local_start 1990-07-28 23:00:00 (Sat)
DateTime::TimeZone::INFINITY, #    local_end
28800,
0,
'PST',
    ],
];

sub olson_version {'2025c'}

sub has_dst_changes {6}

sub _max_year {2035}

sub _new_instance {
    return shift->_init( @_, spans => $spans );
}



1;

