# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.08) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory

#
# Generated from /tmp/HahUrb_roy/asia.  Olson data version 2025c
#
# Do not edit this file directly.
#
package DateTime::TimeZone::Asia::Seoul;

use strict;
use warnings;
use namespace::autoclean;

our $VERSION = '2.66';

use Class::Singleton 1.03;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::Asia::Seoul::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
    [
DateTime::TimeZone::NEG_INFINITY, #    utc_start
60186900728, #      utc_end 1908-03-31 15:32:08 (Tue)
DateTime::TimeZone::NEG_INFINITY, #  local_start
60186931200, #    local_end 1908-04-01 00:00:00 (Wed)
30472,
0,
'LMT',
    ],
    [
60186900728, #    utc_start 1908-03-31 15:32:08 (Tue)
60305268600, #      utc_end 1911-12-31 15:30:00 (Sun)
60186931328, #  local_start 1908-04-01 00:02:08 (Wed)
60305299200, #    local_end 1912-01-01 00:00:00 (Mon)
30600,
0,
'KST',
    ],
    [
60305268600, #    utc_start 1911-12-31 15:30:00 (Sun)
61368332400, #      utc_end 1945-09-07 15:00:00 (Fri)
60305301000, #  local_start 1912-01-01 00:30:00 (Mon)
61368364800, #    local_end 1945-09-08 00:00:00 (Sat)
32400,
0,
'JST',
    ],
    [
61368332400, #    utc_start 1945-09-07 15:00:00 (Fri)
61454473200, #      utc_end 1948-05-31 15:00:00 (Mon)
61368364800, #  local_start 1945-09-08 00:00:00 (Sat)
61454505600, #    local_end 1948-06-01 00:00:00 (Tue)
32400,
0,
'KST',
    ],
    [
61454473200, #    utc_start 1948-05-31 15:00:00 (Mon)
61463455200, #      utc_end 1948-09-12 14:00:00 (Sun)
61454509200, #  local_start 1948-06-01 01:00:00 (Tue)
61463491200, #    local_end 1948-09-13 00:00:00 (Mon)
36000,
1,
'KDT',
    ],
    [
61463455200, #    utc_start 1948-09-12 14:00:00 (Sun)
61480911600, #      utc_end 1949-04-02 15:00:00 (Sat)
61463487600, #  local_start 1948-09-12 23:00:00 (Sun)
61480944000, #    local_end 1949-04-03 00:00:00 (Sun)
32400,
0,
'KST',
    ],
    [
61480911600, #    utc_start 1949-04-02 15:00:00 (Sat)
61494818400, #      utc_end 1949-09-10 14:00:00 (Sat)
61480947600, #  local_start 1949-04-03 01:00:00 (Sun)
61494854400, #    local_end 1949-09-11 00:00:00 (Sun)
36000,
1,
'KDT',
    ],
    [
61494818400, #    utc_start 1949-09-10 14:00:00 (Sat)
61512274800, #      utc_end 1950-03-31 15:00:00 (Fri)
61494850800, #  local_start 1949-09-10 23:00:00 (Sat)
61512307200, #    local_end 1950-04-01 00:00:00 (Sat)
32400,
0,
'KST',
    ],
    [
61512274800, #    utc_start 1950-03-31 15:00:00 (Fri)
61526268000, #      utc_end 1950-09-09 14:00:00 (Sat)
61512310800, #  local_start 1950-04-01 01:00:00 (Sat)
61526304000, #    local_end 1950-09-10 00:00:00 (Sun)
36000,
1,
'KDT',
    ],
    [
61526268000, #    utc_start 1950-09-09 14:00:00 (Sat)
61546834800, #      utc_end 1951-05-05 15:00:00 (Sat)
61526300400, #  local_start 1950-09-09 23:00:00 (Sat)
61546867200, #    local_end 1951-05-06 00:00:00 (Sun)
32400,
0,
'KST',
    ],
    [
61546834800, #    utc_start 1951-05-05 15:00:00 (Sat)
61557717600, #      utc_end 1951-09-08 14:00:00 (Sat)
61546870800, #  local_start 1951-05-06 01:00:00 (Sun)
61557753600, #    local_end 1951-09-09 00:00:00 (Sun)
36000,
1,
'KDT',
    ],
    [
61557717600, #    utc_start 1951-09-08 14:00:00 (Sat)
61637554800, #      utc_end 1954-03-20 15:00:00 (Sat)
61557750000, #  local_start 1951-09-08 23:00:00 (Sat)
61637587200, #    local_end 1954-03-21 00:00:00 (Sun)
32400,
0,
'KST',
    ],
    [
61637554800, #    utc_start 1954-03-20 15:00:00 (Sat)
61672980600, #      utc_end 1955-05-04 15:30:00 (Wed)
61637585400, #  local_start 1954-03-20 23:30:00 (Sat)
61673011200, #    local_end 1955-05-05 00:00:00 (Thu)
30600,
0,
'KST',
    ],
    [
61672980600, #    utc_start 1955-05-04 15:30:00 (Wed)
61683949800, #      utc_end 1955-09-08 14:30:00 (Thu)
61673014800, #  local_start 1955-05-05 01:00:00 (Thu)
61683984000, #    local_end 1955-09-09 00:00:00 (Fri)
34200,
1,
'KDT',
    ],
    [
61683949800, #    utc_start 1955-09-08 14:30:00 (Thu)
61705899000, #      utc_end 1956-05-19 15:30:00 (Sat)
61683980400, #  local_start 1955-09-08 23:00:00 (Thu)
61705929600, #    local_end 1956-05-20 00:00:00 (Sun)
30600,
0,
'KST',
    ],
    [
61705899000, #    utc_start 1956-05-19 15:30:00 (Sat)
61717386600, #      utc_end 1956-09-29 14:30:00 (Sat)
61705933200, #  local_start 1956-05-20 01:00:00 (Sun)
61717420800, #    local_end 1956-09-30 00:00:00 (Sun)
34200,
1,
'KDT',
    ],
    [
61717386600, #    utc_start 1956-09-29 14:30:00 (Sat)
61736139000, #      utc_end 1957-05-04 15:30:00 (Sat)
61717417200, #  local_start 1956-09-29 23:00:00 (Sat)
61736169600, #    local_end 1957-05-05 00:00:00 (Sun)
30600,
0,
'KST',
    ],
    [
61736139000, #    utc_start 1957-05-04 15:30:00 (Sat)
61748231400, #      utc_end 1957-09-21 14:30:00 (Sat)
61736173200, #  local_start 1957-05-05 01:00:00 (Sun)
61748265600, #    local_end 1957-09-22 00:00:00 (Sun)
34200,
1,
'KDT',
    ],
    [
61748231400, #    utc_start 1957-09-21 14:30:00 (Sat)
61767588600, #      utc_end 1958-05-03 15:30:00 (Sat)
61748262000, #  local_start 1957-09-21 23:00:00 (Sat)
61767619200, #    local_end 1958-05-04 00:00:00 (Sun)
30600,
0,
'KST',
    ],
    [
61767588600, #    utc_start 1958-05-03 15:30:00 (Sat)
61779681000, #      utc_end 1958-09-20 14:30:00 (Sat)
61767622800, #  local_start 1958-05-04 01:00:00 (Sun)
61779715200, #    local_end 1958-09-21 00:00:00 (Sun)
34200,
1,
'KDT',
    ],
    [
61779681000, #    utc_start 1958-09-20 14:30:00 (Sat)
61799038200, #      utc_end 1959-05-02 15:30:00 (Sat)
61779711600, #  local_start 1958-09-20 23:00:00 (Sat)
61799068800, #    local_end 1959-05-03 00:00:00 (Sun)
30600,
0,
'KST',
    ],
    [
61799038200, #    utc_start 1959-05-02 15:30:00 (Sat)
61811130600, #      utc_end 1959-09-19 14:30:00 (Sat)
61799072400, #  local_start 1959-05-03 01:00:00 (Sun)
61811164800, #    local_end 1959-09-20 00:00:00 (Sun)
34200,
1,
'KDT',
    ],
    [
61811130600, #    utc_start 1959-09-19 14:30:00 (Sat)
61830487800, #      utc_end 1960-04-30 15:30:00 (Sat)
61811161200, #  local_start 1959-09-19 23:00:00 (Sat)
61830518400, #    local_end 1960-05-01 00:00:00 (Sun)
30600,
0,
'KST',
    ],
    [
61830487800, #    utc_start 1960-04-30 15:30:00 (Sat)
61842580200, #      utc_end 1960-09-17 14:30:00 (Sat)
61830522000, #  local_start 1960-05-01 01:00:00 (Sun)
61842614400, #    local_end 1960-09-18 00:00:00 (Sun)
34200,
1,
'KDT',
    ],
    [
61842580200, #    utc_start 1960-09-17 14:30:00 (Sat)
61870750200, #      utc_end 1961-08-09 15:30:00 (Wed)
61842610800, #  local_start 1960-09-17 23:00:00 (Sat)
61870780800, #    local_end 1961-08-10 00:00:00 (Thu)
30600,
0,
'KST',
    ],
    [
61870750200, #    utc_start 1961-08-09 15:30:00 (Wed)
62683261200, #      utc_end 1987-05-09 17:00:00 (Sat)
61870782600, #  local_start 1961-08-10 00:30:00 (Thu)
62683293600, #    local_end 1987-05-10 02:00:00 (Sun)
32400,
0,
'KST',
    ],
    [
62683261200, #    utc_start 1987-05-09 17:00:00 (Sat)
62696566800, #      utc_end 1987-10-10 17:00:00 (Sat)
62683297200, #  local_start 1987-05-10 03:00:00 (Sun)
62696602800, #    local_end 1987-10-11 03:00:00 (Sun)
36000,
1,
'KDT',
    ],
    [
62696566800, #    utc_start 1987-10-10 17:00:00 (Sat)
62714710800, #      utc_end 1988-05-07 17:00:00 (Sat)
62696599200, #  local_start 1987-10-11 02:00:00 (Sun)
62714743200, #    local_end 1988-05-08 02:00:00 (Sun)
32400,
0,
'KST',
    ],
    [
62714710800, #    utc_start 1988-05-07 17:00:00 (Sat)
62728016400, #      utc_end 1988-10-08 17:00:00 (Sat)
62714746800, #  local_start 1988-05-08 03:00:00 (Sun)
62728052400, #    local_end 1988-10-09 03:00:00 (Sun)
36000,
1,
'KDT',
    ],
    [
62728016400, #    utc_start 1988-10-08 17:00:00 (Sat)
DateTime::TimeZone::INFINITY, #      utc_end
62728048800, #  local_start 1988-10-09 02:00:00 (Sun)
DateTime::TimeZone::INFINITY, #    local_end
32400,
0,
'KST',
    ],
];

sub olson_version {'2025c'}

sub has_dst_changes {12}

sub _max_year {2035}

sub _new_instance {
    return shift->_init( @_, spans => $spans );
}



1;

