name: Prune old unpulled container package versions

on:
  schedule:
    - cron: '0 5 * * 0'     # Weekly on Sundays at 05:00 UTC
  workflow_dispatch:

jobs:
  prune:
    runs-on: ubuntu-latest
    name: Delete old test images
    steps:
      - uses: snok/container-retention-policy@v3.1.0
        with:
          account: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: "lyrionmusicserver"
          cut-off: 180d
          tag-selection: untagged
          dry-run: true
